### ISSUE TITLE
Report is not import, matching filenames failure.

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/vanadis-bot#22]
$ ./import-report.py -p quagga -r 258f3da ~/Sources/quagga.cppcheck/e3f623b.cppcheck
19.12 17:52:59 GET from http://127.0.0.1:8000/quagga/258f3da?view=full
19.12 17:52:59 Starting new HTTP connection (1): 127.0.0.1
19.12 17:53:00 Server request take a 1383ms
Traceback (most recent call last):
  File "./import-report.py", line 33, in <module>
    report = Report(open(a, 'r'), filelist)
  File "/home/dron/Projects/vanadis-bot/bot/Report.py", line 21, in __init__
    filename = filelist.canonize(i.location.file)
  File "/home/dron/Projects/vanadis-bot/bot/Filelist.py", line 14, in canonize
    if p.endswith(fn) or fn.endswith(p):
AttributeError: 'NoneType' object has no attribute 'endswith'

I'm select other version, i'm know. It's not principle.

**Comment by DronMDF** [comment]
Clang is same problem
dron@mdf-work:~/Projects/vanadis-bot$ ./import-report.py -p quagga -r 258f3da ~/Sources/quagga.clang/ff1dd55.clang
19.12 17:57:03 GET from http://127.0.0.1:8000/quagga/258f3da?view=full
19.12 17:57:03 Starting new HTTP connection (1): 127.0.0.1
19.12 17:57:05 Server request take a 1361ms
Traceback (most recent call last):
  File "./import-report.py", line 33, in <module>
    report = Report(open(a, 'r'), filelist)
  File "/home/dron/Projects/vanadis-bot/bot/Report.py", line 21, in __init__
    filename = filelist.canonize(i.location.file)
  File "/home/dron/Projects/vanadis-bot/bot/Filelist.py", line 14, in canonize
    if p.endswith(fn) or fn.endswith(p):
AttributeError: 'NoneType' object has no attribute 'endswith'
